spring:

  datasource:
    url: jdbc:h2:mem:maindb

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

server:
  port: 8080

springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger-ui.html
